### ISSUE TITLE
vmi address space root access

### ISSUE THREAD

**Issue by asabellico** [libvmi/python#24]
Some months ago I successfully used libvmi+python bindings+volatility.
Now using the following setup:
* xen 4.9
* libvmi latest (@d6602ee)
* python bindings latest (@6e38865)
* volatility 2.6

i always get :
...
DEBUG   : volatility.debug    : Applying modification from Win7Win32KCoreClasses
VMI_ERROR: Could not find a live guest VM or file to use.
VMI_ERROR: Opening a live guest VM requires root access.
DEBUG   : volatility.debug    : Failed instantiating (exception): VMI_FAILURE

even running volatility as root:
sudo vol.py -d -l vmi:///test1 --profile=Win7SP1x86 pslist

What could be the problem?

**Comment by Wenzel** [comment]
Hi,

i would advise you to recompile `libvmi` with all the debug flags enabled (`libvmi/debug.h`, uncomment the `#define`: https://github.com/libvmi/libvmi/blob/master/libvmi/debug.h#L56)

and post the result here.

**Comment by asabellico** [comment]
Hello @Wenzel ,
 with the libvmi debug enabled i only get this extra line:
**The running Xen version is 4.9

**Comment by Wenzel** [comment]
What happens if you run:
~~~
sudo python3 -c 'from libvmi import Libvmi; Libvmi("test1")'
~~~

(should be the right syntax, i'm not running Xen, so i can't test this :) )

**Comment by Wenzel** [comment]
it was expected, because in the volatility plugin, we specify `partial=True`
https://github.com/libvmi/python/blob/master/volatility/vmi.py#L56

Which means no configuration, no need for offsets.

You can add this option in the python command line and see what it does.

**Comment by asabellico** [comment]
yep i've seen that before .. yes, with 

sudo python -c 'from libvmi import Libvmi; Libvmi("test1", partial=True)' 

no error:
**The running Xen version is 4.9
--found Xen
LibVMI Version 0.13.0
LibVMI Driver Mode 0
**The running Xen version is 4.9
--completed driver init.
--got id from name (test1 --> 124)
**set image_type = test1
**set vm_type HVM
--xen: setup live mode
**set allocated_ram_size = 10004d000, max_physical_address = 0x110052000

**Comment by asabellico** [comment]
Anyway the same error, happen also with old libvmi+bindings versions:

DEBUG : volatility.debug : Applying modification from Win7Win32KCoreClasses
VMI_ERROR: Could not find a live guest VM or file to use.
VMI_ERROR: Opening a live guest VM requires root access.
DEBUG : volatility.debug : Failed instantiating (exception): VMI_FAILURE

**Comment by Wenzel** [comment]
You see these messages because Libvmi couldn't initialize either Xen or KVM or the file access:
https://github.com/libvmi/libvmi/blob/dfce146926ceb5f7587659c516ee77502cd014f9/libvmi/driver/driver_interface.c#L80

Try with:
~~~
sudo vol.py -d -l vmi://test1 --profile=Win7SP1x86 pslist
~~~

(I removed one `/` after `vmi://`)
I think that `libvmi` is searching for a vm named `/test1`, which ofc doesn't exist.

**Comment by Wenzel** [comment]
If it works, then we need to update the documentation.

**Comment by asabellico** [comment]
Failed instantiating (exception): global name 'CR3' is not defined

mm.. this seems strange. is it not the latest libvmi commit paired with this pyvmi?

**Comment by asabellico** [comment]
Anyway it goes ahead but cannot import CR3 from libvmi

**Comment by asabellico** [comment]
Trying to import X86Reg instead of CR3 and then using X86Reg.CR3 in the __init__ but it fails with:
DEBUG   : volatility.debug    : Failed instantiating (exception): an integer is required

no idea where this exception happened.. i suppose in :     
self.dtb = self.vmi.get_vcpu_reg(X86Reg.CR3, 0)

**Comment by Wenzel** [comment]
Ah, yes

It's an Enum

Use X86Reg.CR3.value

**Comment by asabellico** [comment]
That's right. it begin to read pfn and then fails at 
--xen_get_memory_pfn failed on pfn=0xa0

it is like i've already seen that address 0xa0

**Comment by asabellico** [comment]
Based on what I observe in volatility/scan.py:114:

# Populate the buffer with data
# We use zread to scan what we can because there are often invalid
# pages in the DTB
data = address_space.zread(current_offset, l)

zread function should not fail when reading invalid pages. 
Does exist a way to call Libvmi.read_pa() to not fail in case of invalid pages?

**Comment by asabellico** [comment]
Even though I modified the VMIAddressSpace.zread like this:

def zread(self, addr, length):
        buffer, bytes_read = self.vmi.read_pa(addr, length, padding=True)         
        return buffer

i'm getting no error, but an empty pslist.. does the padding=True parameter broke something?

**Comment by asabellico** [comment]
ok! it is working now! should I do a pull request @Wenzel ?

**Comment by Wenzel** [comment]
congrats @asabellico !

yes, please make a PR, and i will review it

**Comment by asabellico** [comment]
do I have permissions to do that? i'm trying to push a new branch with the fix, but i get deny

**Comment by Wenzel** [comment]
Did you forked the repo beforehand ?
You can make a PR from your repo to this one
