### ISSUE TITLE
Python 2.7 compatibility broken.

### ISSUE THREAD

**Issue by wiredrat** [libvmi/python#37]
`raise ... from e` syntax is not compatible with Python 2.7
https://github.com/libvmi/python/blob/a1d7dbe10eb1c295c87be0f0ce671672d006c314/libvmi/libvmi.py#L74-L75
https://github.com/libvmi/python/blob/a1d7dbe10eb1c295c87be0f0ce671672d006c314/libvmi/libvmi.py#L85-L86

**Comment by Wenzel** [comment]
Indeed @wiredrat 
If you know how to check this with a Travis test, please make a PR.
I will update the bindings soonish.
Thanks

**Comment by wiredrat** [comment]
I can't help you with Travis, but this commit 0000fbf775a074b50d2168ae0fa9e8b7fcfe76ff works for this kind of issues.
However I can PR the fix for the issue if you need it.

**Comment by Wenzel** [comment]
Ah yes, Travis failed last time, so the check is already here:
https://travis-ci.org/libvmi/python/jobs/475862018

If you could make a PR with the fix, it would be very helpful.
Maybe `futurize` can give you the best fix, compatible python2 and 3 ?

**Comment by wiredrat** [comment]
`future.utils` has `raise_from()` function that does the trick. The above PR "works for me" :)
