### ISSUE TITLE
VMIInitData not exported

### ISSUE THREAD

**Issue by logankonopatzke** [libvmi/python#63]
Attempting to run the kvmi_demos branch, I get the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/vmidbg", line 5, in <module>
    from vmidbg.__main__ import main
  File "/usr/local/lib/python3.6/dist-packages/vmidbg/__main__.py", line 22, in <module>
    from vmidbg.libvmistub import LibVMIStub
  File "/usr/local/lib/python3.6/dist-packages/vmidbg/libvmistub.py", line 8, in <module>
    from libvmi import Libvmi, INIT_DOMAINNAME, INIT_EVENTS, VMIOS, LibvmiError, X86Reg, VMIInitData
ImportError: cannot import name 'VMIInitData'
`

I'm using KVM with the KVM-VMI support and the latest version of LibVMI.

**Comment by Wenzel** [comment]
Hi,

the `kvmi_demos` is still opened in this PR: https://github.com/libvmi/python/pull/59
it only contains the demos of my presentation at hack.lu 2019, and not the rest of the glue to use the new KVM driver of Libvmi.

In the last slide, I indicated that it was still a WIP, and that you needed to switch on specific branches to get KVM support in libvmi/python:
![image](https://user-images.githubusercontent.com/964610/89390477-124cfe00-d707-11ea-95b5-ece6ecc69e08.png)

However this `init_data` branch is bit old too.

I have been focused on getting the maximum of this work upstream,
and now that https://github.com/libvmi/libvmi/pull/844 has been merged in Libvmi,
I will update the bindings soon, and check that `vmidbg` loads properly.

Thank you very much for reporting this issue.

**Comment by Wenzel** [comment]
@logankonopatzke you should be able to use this branch: https://github.com/libvmi/python/pull/44

**Comment by Wenzel** [comment]
solved by #44

**Comment by logankonopatzke** [comment]
Working as expected on my end, thank you for all your hard work!

**Comment by Wenzel** [comment]
@logankonopatzke thanks for your feedback, I'm really happy to hear this :+1:
